const { Octokit } = require('@octokit/rest');
require('dotenv').config();

/**
 * GitHub Service for Automatic Pull Request Creation
 */
class GitHubService {
  constructor() {
    this.token = process.env.GITHUB_TOKEN;
    this.owner = process.env.GITHUB_OWNER;
    this.repo = process.env.GITHUB_REPO;
    this.baseBranch = process.env.GITHUB_BRANCH || 'main';
    
    if (!this.token) {
      console.warn('GitHub token not configured. PR creation will be disabled.');
      this.octokit = null;
      return;
    }

    this.octokit = new Octokit({
      auth: this.token
    });
  }

  /**
   * Create a pull request with the generated fix
   */
  async createFixPR(incident, fixData) {
    if (!this.octokit) {
      console.warn('GitHub not configured. Skipping PR creation.');
      return {
        success: false,
        error: 'GitHub not configured',
        prUrl: null
      };
    }

    try {
      // Create a new branch for the fix
      const branchName = `autofix/${incident.alertName.toLowerCase()}-${incident.id}`;
      
      // Get the base branch reference
      const baseRef = await this.octokit.git.getRef({
        owner: this.owner,
        repo: this.repo,
        ref: `heads/${this.baseBranch}`
      });

      const baseSha = baseRef.data.object.sha;

      // Create new branch
      await this.octokit.git.createRef({
        owner: this.owner,
        repo: this.repo,
        ref: `refs/heads/${branchName}`,
        sha: baseSha
      });

      console.log(`Created branch: ${branchName}`);

      // Commit changes for each file
      for (const file of fixData.files) {
        await this.commitFile(branchName, file.path, file.changes, incident);
      }

      // Create pull request
      const prTitle = `🤖 AutoFix: ${incident.alertName} - ${incident.description.substring(0, 50)}`;
      const prBody = this.generatePRDescription(incident, fixData);

      const pr = await this.octokit.pulls.create({
        owner: this.owner,
        repo: this.repo,
        title: prTitle,
        head: branchName,
        base: this.baseBranch,
        body: prBody
      });

      console.log(`Created PR #${pr.data.number}: ${pr.data.html_url}`);

      // Add labels
      await this.addLabels(pr.data.number, incident);

      return {
        success: true,
        prUrl: pr.data.html_url,
        prNumber: pr.data.number,
        branch: branchName
      };
    } catch (error) {
      console.error('Error creating PR:', error.message);
      return {
        success: false,
        error: error.message,
        prUrl: null
      };
    }
  }

  /**
   * Commit a file to the branch
   */
  async commitFile(branch, filePath, content, incident) {
    try {
      // Get current file (if exists)
      let currentFile;
      let currentSha;
      
      try {
        currentFile = await this.octokit.repos.getContent({
          owner: this.owner,
          repo: this.repo,
          path: filePath,
          ref: branch
        });
        currentSha = currentFile.data.sha;
      } catch (error) {
        // File doesn't exist, will create new
        currentSha = null;
      }

      // Create or update file
      const commitMessage = `🤖 AutoFix: ${incident.alertName} in ${filePath}

Incident ID: ${incident.id}
Root Cause: ${incident.rootCause}

This fix was automatically generated by BobAutoOps AI.`;

      await this.octokit.repos.createOrUpdateFileContents({
        owner: this.owner,
        repo: this.repo,
        path: filePath,
        message: commitMessage,
        content: Buffer.from(content).toString('base64'),
        branch: branch,
        sha: currentSha
      });

      console.log(`Committed changes to ${filePath}`);
    } catch (error) {
      console.error(`Error committing file ${filePath}:`, error.message);
      throw error;
    }
  }

  /**
   * Generate PR description with incident details
   */
  generatePRDescription(incident, fixData) {
    return `## 🤖 Automated Fix by BobAutoOps

### Incident Details
- **Alert:** ${incident.alertName}
- **Severity:** ${incident.severity}
- **Incident ID:** ${incident.id}
- **Detected:** ${incident.timestamp}
- **Service:** ${incident.service}

### Root Cause Analysis
${incident.rootCause}

### Fix Description
${fixData.fixDescription}

### Changes Made
${fixData.files.map(f => `- \`${f.path}\``).join('\n')}

### Affected Files
${incident.affectedFiles.map(f => `- \`${f}\``).join('\n')}

### Testing Recommendations
${fixData.testSuggestions.map((test, i) => `${i + 1}. ${test}`).join('\n')}

### AI Analysis Confidence
${(incident.confidence * 100).toFixed(0)}%

---

**⚠️ Important:** This PR was automatically generated by AI. Please review carefully before merging.

**Generated by:** BobAutoOps v1.0 | IBM watsonx AI
**Postmortem:** Available at \`/postmortem/${incident.id}\`
`;
  }

  /**
   * Add labels to the PR
   */
  async addLabels(prNumber, incident) {
    try {
      const labels = ['autofix', 'bot'];
      
      // Add severity label
      if (incident.severity) {
        labels.push(`severity:${incident.severity}`);
      }

      // Add alert type label
      if (incident.alertName) {
        labels.push(`alert:${incident.alertName.toLowerCase()}`);
      }

      await this.octokit.issues.addLabels({
        owner: this.owner,
        repo: this.repo,
        issue_number: prNumber,
        labels: labels
      });

      console.log(`Added labels to PR #${prNumber}`);
    } catch (error) {
      console.error('Error adding labels:', error.message);
      // Non-critical error, don't throw
    }
  }

  /**
   * Add comment to PR with additional information
   */
  async addPRComment(prNumber, comment) {
    try {
      await this.octokit.issues.createComment({
        owner: this.owner,
        repo: this.repo,
        issue_number: prNumber,
        body: comment
      });
    } catch (error) {
      console.error('Error adding PR comment:', error.message);
    }
  }

  /**
   * Check if GitHub is configured
   */
  isConfigured() {
    return this.octokit !== null && this.owner && this.repo;
  }

  /**
   * Get repository information
   */
  async getRepoInfo() {
    if (!this.octokit) {
      return null;
    }

    try {
      const repo = await this.octokit.repos.get({
        owner: this.owner,
        repo: this.repo
      });

      return {
        name: repo.data.full_name,
        url: repo.data.html_url,
        defaultBranch: repo.data.default_branch
      };
    } catch (error) {
      console.error('Error getting repo info:', error.message);
      return null;
    }
  }
}

module.exports = new GitHubService();

// Made with Bob
